version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db-go-tweets
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=go-tweets
    volumes:
      - /home/vitalik/workspace/go/db-go-tweets:/var/lib/mysql
        
